language: python

python:
  - "3.6"

stages:
  - name: push
    if: fork = false AND branch = master

jobs:
  include:
    - stage: push
      script:
        - curl -L https://git.io/get_helm.sh | bash
        - pip3 install operator-courier
        - make push/all QUAY_USERNAME="${QUAY_USERNAME}" QUAY_PASSWORD="${QUAY_PASSWORD}" REPO="integreatly"
